{"name": "test_sum", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_file.py:11: AssumptionFailure\n>>\tpytest.assume(4 == 3)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_file.py:11: AssumptionFailure\nE               >>\tpytest.assume(4 == 3)\nE               AssertionError: assert False\n\n/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py:692: FailedAssumption"}, "start": 1586598036449, "stop": 1586598036490, "uuid": "983ad0bc-922c-4349-82b3-97b0c0627411", "historyId": "6167e6b6e982eacf32093f335c8b5f5d", "testCaseId": "2987f5928f89bb3443b4e2795a94a952", "fullName": "test_file#test_sum", "labels": [{"name": "suite", "value": "test_file"}, {"name": "host", "value": "JdeMacBook-Pro.local"}, {"name": "thread", "value": "7422-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file"}]}